apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: default
spec:
  schedule: "22 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quote-batch
            image: 702867482623.dkr.ecr.ap-northeast-2.amazonaws.com/myapp/stock-batch
            imagePullPolicy: Always
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: prod
              - name: SPRING_BATCH_JOB_NAMES
                value: QUOTE_JOB
          restartPolicy: Never
          imagePullSecrets:
          - name: regcred
